ansible/roles/kubernetes/tasks/gen_certs.yml

Set the proper permissions for k8s certs

---

ansible/cluster.retry
ansible/roles/nuage_common/defaults/main.yml
ansible/roles/nuage_master/defaults/main.yml
ansible/roles/nuage_master/handlers/main.yml
ansible/roles/nuage_master/meta/main.yml
ansible/roles/nuage_node/handlers/main.yml
ansible/roles/nuage_node/meta/main.yml
ansible/roles/nuage_node/tasks/iptables.yaml

Added iptable rules for PAT to underlay

PAT iptables

---

nuagekubemon/client/nuagevsdclient.go

Disable PAT to underlay on the domain

---

nuagekubemon/api/api.go
nuagekubemon/client/nuageclusterclient.go
nuagekubemon/client/nuagevsdclient.go
nuagekubemon/policy/resourcemanager.go

@abhat Changes for adding support for kubernetes namespace annotations

Changes added for namespace annotations

---

nuagekubemon/client/nuagevsdclient.go
nuagekubemon/config/types.go
nuagekubemon/monitor/monitor.go
nuagekubemon/nuage-openshift-monitor.yaml.template
nuagekubemon/nuagekubemon.yaml.template
nuagekubemon/policy/resourcemanager.go
nuagekubemon/vendor/github.com/nuagenetworks/go-bambou/bambou/error.go
nuagekubemon/vendor/github.com/nuagenetworks/go-bambou/bambou/session.go
nuagekubemon/vendor/github.com/nuagenetworks/nuagepolicyapi/implementer/implementer.go
nuagekubemon/vendor/github.com/nuagenetworks/vspk-go/vspk/session.go

Modified PR with certificate changes for k8s/ose

Modified PR with certificate changes for k8s/ose

---

ansible/nodes
ansible/roles/nuage-master/defaults/main.yml
ansible/roles/nuage-master/tasks/main.yml
ansible/roles/nuage-master/templates/nuagekubemon.yaml.j2
ansible/roles/nuage-node/tasks/main.yml
ansible/roles/nuage-node/templates/vsp-k8s.j2
ansible/roles/nuage-node/vars/main.yml
manual-installation/README.md

Ansible installer changes to use Nuage K8S CNI plugin

Ansible installer changes to use Nuage K8S CNI plugin

---

nuagekubemon/api/api.go
nuagekubemon/client/nuagevsdclient.go

Debug PR for VRS-8375

---

ansible/roles/nuage-master/tasks/serviceaccount.yml

Fix for VRS-8492

---

ansible/roles/nuage-master/tasks/serviceaccount.yml

Port fix for VRS-8492 to 4.0

---

ansible/roles/nuage-master/tasks/serviceaccount.yml

Retry fix for VRS-8492

---

ansible/roles/nuage-master/tasks/serviceaccount.yml

Revert fix for VRS-8492 on 4.0

Revert fix for VRS-8492 on 4.0

---

ansible/roles/nuage-master/tasks/serviceaccount.yml

Port fix for VRS-8492 to 5.0 branch

Port fix for VRS-8492 to 5.0 branch

---

ansible/roles/nuage-master/tasks/serviceaccount.yml

Port fir for VRS-8492 to 0.0

---

ansible/nodes
ansible/playbooks/deploy-cluster.yml
ansible/roles/lb/defaults/main.yml
ansible/roles/lb/handlers/main.yml
ansible/roles/lb/meta/main.yml
ansible/roles/lb/tasks/iptables.yml
ansible/roles/lb/tasks/main.yml
ansible/roles/lb/templates/haproxy.cfg.j2
ansible/roles/nuage-common/defaults/main.yml
ansible/roles/nuage-master/tasks/serviceaccount.yml
ansible/roles/nuage-master/templates/nuagekubemon.yaml.j2
ansible/roles/nuage-node/tasks/main.yml
ansible/roles/nuage-node/templates/vsp-k8s.j2
ansible/roles/nuage-node/vars/main.yml

ansible changes to support K8S HA install

---

nuagekubemon/Dockerfile
nuagekubemon/configure-master.sh
nuagekubemon/scripts/build-nuage-monitor-docker.sh

Containerize monitor and use daemon sets for installation [WIP]

Containerize monitor and use daemon sets for installation [WIP]

---

ansible/nodes

Fix nodes file

---

ansible/roles/nuage-daemonset/files/nuage-node-config-daemonset.yaml

Add Nuage CNI yaml as config maps in node daemon sets

Add Nuage CNI yaml as config maps in node daemon sets

---

ansible/roles/nuage-daemonset/files/nuage-node-config-daemonset.yaml

Fix for VRS-9910

---

ansible/roles/nuage-daemonset/files/nuage-master-config-daemonset.yaml
nuagekubemon/configure-master.sh

Fix for VRS-10916

---

ansible/roles/nuage-daemonset/files/nuage-infra-pod-config-daemonset.yaml
ansible/roles/nuage-daemonset/tasks/main.yml
nuagekubemon/nuage-infra/Dockerfile
nuagekubemon/nuage-infra/install-nuage-infra-pod.sh
nuagekubemon/scripts/build-nuage-infra-docker-image.sh

Changes to support Node Port for k8s with Nuage

Changes to support Node Port for k8s with Nuage

---

kubernetes-standalone-deployment/kubernetes-1-installation.rst

Update daemon set config for monitor

Update daemon set config for monitor

---

nuagekubemon/client/nuageclusterclient.go
nuagekubemon/client/nuagevsdclient.go
nuagekubemon/configure-master.sh

Monitor changes to support complete daemon sets Nuage installation

Monitor changes to support complete daemon sets Nuage installation

---

daemonset-templates/nuage-infra-pod-config-daemonset.yaml
daemonset-templates/nuage-master-config-daemonset.yaml
daemonset-templates/nuage-node-config-daemonset.yaml

Move daemon set yaml files to seperate folder

Move daemon set yaml files to seperate folder

---

ansible/roles/nuage-daemonset/files/nuage-master-config-daemonset.yaml
daemonset-templates/nuage-master-config-daemonset.yaml

Update master node daemon set file template

Update master node daemon set file template

---

nuagekubemon/client/nuagevsdclient.go

Fix for OSE/Atomic monitor for 5.2.1

Fix for OSE/Atomic monitor for 5.2.1

---

ansible/roles/nuage-daemonset/files/nuage-master-config-daemonset.yaml
ansible/roles/nuage-daemonset/files/nuage-node-config-daemonset.yaml
daemonset-templates/nuage-master-config-daemonset.yaml
daemonset-templates/nuage-node-config-daemonset.yaml

Add missing config in Nuage daemon set file

Add missing config in Nuage daemon set file

---

README.md

Update README with required 5.2.1 note

Update README with required 5.2.1 note

---

daemonset-templates/nuage-master-config-daemonset.yaml
daemonset-templates/nuage-node-config-daemonset.yaml

Update master and node daemonsets to support k8s 1.14

Fix PROD-9398

---

nuagekubemon/strongswan-docker/Makefile

We need to be able to run build also on sites where we have to use proxy server.

INF-9996: Specify proxy settings for docker build
